# This workflow runs every day to clean up the resources created by the Terraform configuration

name: "Destroy"

on:
  schedule:
    # Run every day at 07:00 UTC
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_mssql_azuread_administrator_object_id: ${{ secrets.mssql_azuread_administrator_object_id }}
  TF_VAR_mssql_administrator_login: ${{ secrets.mssql_administrator_login }}
  TF_VAR_mssql_administrator_password: ${{ secrets.mssql_administrator_password }}
  CONFIGURATION: release

jobs:
  build:
    name: "Destroy"
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v5

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        run: terraform init -no-color -input=false

      - name: Terraform Init
        run: terraform init -no-color -input=false

      - name: Terraform Apply
        run: terraform apply -destroy -auto-approve -input=false -no-color
